# Generated by Django 3.0.7 on 2020-06-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesslist',
            name='image',
        ),
    ]
